import { TypeCookies } from './types';  // Importing the TypeCookies type

const ytCookies: TypeCookies[] = [[
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.778289,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "4owSSo-JJjxpkpdE/AZQRSRAD79O6bUE9e",
        "id": 1
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.777694,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000nggkNVLWt1H6fcNKHJdDHtvjK9aRqnfoCDKhDCMuk7vPHD00G4j_HkDa-27dpj7ZXIUDAAACgYKAZ0SARcSFQHGX2MivfOT4gBZqKky1ehzI0Y0wRoVAUF8yKp6p_imOCt-oy4trsk3OY8T0076",
        "id": 2
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1758134183.311191,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzWNpFSX7jk4T-5c91_1rs7sI04Y1aJjUVrPUNpCLcF0IhHAOTz_RqjCH0xj8u1GqE4GaII",
        "id": 3
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1758134096.505386,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjEBQlrA-INexQAhRIEWCCMf7_c4QK5GLsqovA-4umf_1BzmzxUCPQW8wJi1VrLjTnz_EAA",
        "id": 4
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.778412,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "4owSSo-JJjxpkpdE/AZQRSRAD79O6bUE9e",
        "id": 5
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.777809,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000nggkNVLWt1H6fcNKHJdDHtvjK9aRqnfoCDKhDCMuk7vPHD00fOD85wd7ZluFFyn0psOaqgACgYKAQoSARcSFQHGX2MiNKkBZrCtIFmspphHPdcGxRoVAUF8yKpaqBwGf1yoNbWnp_-CS4Ei0076",
        "id": 6
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1758134183.311317,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzXd7uniSBD9bu0uXx7XRjD2GLwxBh6b9PWsWWVb9D3WX55U810hMWZwR-2t1e7D62zBYQ",
        "id": 7
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1758134096.505678,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjEBQlrA-INexQAhRIEWCCMf7_c4QK5GLsqovA-4umf_1BzmzxUCPQW8wJi1VrLjTnz_EAA",
        "id": 8
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.778101,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CQyg3A4aULLZmRXS/A4UBq0oAiCfrYglUR",
        "id": 9
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.777918,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AbNMuXfsSfh7X0yY5",
        "id": 10
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1728923585.684673,
        "hostOnly": false,
        "httpOnly": true,
        "name": "LOGIN_INFO",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFmmF2swRQIgT6Tdrbu7Zxg7jtJL2YgMwziFGl9WjozU8Lgy2n4yAd4CIQDITTRaL45r6JtcqvDdgDtk9qag_1cWfuywtRDaRP7roA:QUQ3MjNmel9LM1BMTFJLWVVwbC1Tc2JoX3JCRXlldGNvTzJ0bjRDcUNtUDBiQjE3U0NTMXZqRm00clF0dDcyR2VEYWtRY05Hd0R0UjBhRC12bzNrdExIUU5QU0VqUmdOTkdaWXVsWnRka3NqSlRwNE04SEVzQmNKUDlXMlhCRVpFM1RMQ0l1bXZ2bEJwMkhjSTFuZ1VXUHBPVnpTdUlVSXZR",
        "id": 11
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1761151480.26278,
        "hostOnly": false,
        "httpOnly": false,
        "name": "PREF",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "tz=Asia.Karachi&f7=100&f5=30000",
        "id": 12
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.778195,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "4owSSo-JJjxpkpdE/AZQRSRAD79O6bUE9e",
        "id": 13
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.777045,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a000nggkNVLWt1H6fcNKHJdDHtvjK9aRqnfoCDKhDCMuk7vPHD00Felrr8__KMNYaGiznvsUewACgYKAVwSARcSFQHGX2MillUkcFri3xP701-It4e1tBoVAUF8yKopfR1bfZqbzKPQjC67j-my0076",
        "id": 14
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1758134183.310917,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzWaLmvum-ttE0UXw7KrrR2Z3DTEqnIRLF9tKEU0tKpczWIRp7xlx_zN6Uu70egiaKW4O9w",
        "id": 15
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1759660214.778009,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Ahh2qtTkbXiMLlkMA",
        "id": 16
    }
    ]